// Builds resources/modules/traffic/{popgroups.xml,groups.lua}: MRI traffic plus vanilla and DLC cars per group.
// node tools/traffic/build.cjs <path to DurtyFree gta-v-data-dumps vehicles.json>
const fs = require('fs')
const path = require('path')

const here = __dirname
const out = path.join(here, '../../resources/modules/traffic')
const vehicles = JSON.parse(fs.readFileSync(process.argv[2] || 'C:/Github/gta-v-data-dumps/vehicles.json', 'utf8'))

const GROUPS = [
  { id: 'VEH_POOR', label: 'Bairros pobres', dlc: ['poor'] },
  { id: 'VEH_MID', label: 'Classe média', dlc: ['avg', 'plain'] },
  { id: 'VEH_RICH', label: 'Bairros ricos', dlc: ['rich'] },
  { id: 'VEH_LARGE_CITY', label: 'Centro da cidade', dlc: ['poor', 'avg'] },
  { id: 'VEH_FREEWAY', label: 'Rodovias', dlc: ['avg'] },
  { id: 'VEH_COUNTRYSIDE_ONROAD', label: 'Interior, no asfalto', dlc: ['utility'] },
  { id: 'VEH_COUNTRYSIDE_OFFROAD', label: 'Interior, na terra', dlc: ['offroad'] },
  { id: 'VEH_BIKES', label: 'Motos', dlc: ['bike'] },
]

const BAD_FLAG = /ROCKET|JUMP|GLIDER|TANK|LAW_ENFORCEMENT|EMERGENCY_SERVICE|DONT_SPAWN_AS_AMBIENT|WEAPON_SPIKE|WEAPON_BLADE|TURRET|SPAWN_ON_TRAILER/
const CLASSES = ['COMPACT', 'SEDAN', 'SUV', 'COUPE', 'MUSCLE', 'SPORT_CLASSIC', 'SPORT', 'SUPER', 'OFF_ROAD', 'VAN', 'MOTORCYCLE']

function kinds(v) {
  const f = v.Flags || []
  if (v.Class === 'MOTORCYCLE') return ['bike']
  if (v.Class === 'OFF_ROAD') return ['offroad']
  const list = []
  if (f.includes('FLAG_POOR_CAR')) list.push('poor')
  else if (f.includes('FLAG_AVERAGE_CAR')) list.push('avg')
  else if (f.includes('FLAG_RICH_CAR') || f.includes('FLAG_SPORTS') || ['MUSCLE', 'SPORT_CLASSIC', 'SPORT', 'SUPER'].includes(v.Class)) list.push('rich')
  else list.push('plain')
  if (v.Class === 'SUV' || v.Class === 'VAN') list.push('utility')
  return list
}

const byName = new Map(vehicles.map((v) => [v.Name.toLowerCase(), v]))
const ambient = vehicles.filter((v) =>
  ['CAR', 'BIKE'].includes(v.Type) && CLASSES.includes(v.Class) && !(v.Weapons && v.Weapons.length) &&
  !v.HasArmoredWindows && !v.HasSirens && !(v.Flags || []).some((f) => BAD_FLAG.test(f)))

function readGroups(xml) {
  const veh = xml.slice(xml.indexOf('<vehGroups>'), xml.indexOf('</vehGroups>'))
  const map = {}
  for (const chunk of veh.split('\n    <Item>\n').slice(1)) {
    const name = chunk.match(/^\s*<Name>([^<]+)/)[1]
    map[name] = [...chunk.matchAll(/<Item>\s*<Name>([^<]+)<\/Name>/g)].map((m) => m[1].toLowerCase())
  }
  return map
}

const mriXml = fs.readFileSync(path.join(here, 'popgroups.mri.xml'), 'utf8')
const mri = readGroups(mriXml)
const vanilla = readGroups(fs.readFileSync(path.join(here, 'popgroups.vanilla.xml'), 'utf8'))

const enabled = new Set()
let xml = mriXml
const lua = ['-- Generated by tools/traffic/build.cjs; edit the tool, not this file.', 'return {']
for (const group of GROUPS) {
  const models = [...new Set([
    ...mri[group.id],
    ...vanilla[group.id],
    ...ambient.filter((v) => kinds(v).some((k) => group.dlc.includes(k))).map((v) => v.Name.toLowerCase()),
  ])].filter((m) => byName.has(m) || mri[group.id].includes(m))
  mri[group.id].forEach((m) => enabled.add(m))

  const items = models.map((m) => `        <Item>\n          <Name>${m}</Name>\n          <Variations type="NULL" />\n        </Item>`).join('\n')
  const re = new RegExp(String.raw`(<Name>${group.id}</Name>\s*<models>)[^]*?(\n      </models>)`)
  if (!re.test(xml)) throw new Error('group not found: ' + group.id)
  xml = xml.replace(re, (_, a, b) => `${a}\n${items}${b}`)

  const label = (m) => (byName.get(m)?.DisplayName?.English || m).replace(/'/g, "\\'")
  lua.push(`    { id = '${group.id}', label = '${group.label}', models = {`)
  for (const m of models) lua.push(`        { '${m}', '${label(m)}' },`)
  lua.push('    } },')
}
lua.push('}', '')

fs.writeFileSync(path.join(out, 'popgroups.xml'), xml)
fs.writeFileSync(path.join(out, 'groups.lua'), lua.join('\n'))
fs.writeFileSync(path.join(out, 'defaults.lua'), ['-- Generated by tools/traffic/build.cjs: the MRI traffic, every other model starts off.', 'return {', ...[...enabled].sort().map((m) => `    '${m}',`), '}', ''].join('\n'))
console.log(GROUPS.map((g) => `${g.id} ${readGroups(xml)[g.id].length}`).join('\n'), '\nenabled', enabled.size)
