Mri.module({
    id = 'indestructibleprops',
    label = 'Postes indestrutíveis',
    category = 'world',
    description = 'Postes, semáforos e hidrantes não quebram nem saem do lugar.',
    defaults = {
        enabled = true,
        delay = 1500,
        models = {
            'prop_traffic_03b',
            'prop_traffic_lightset_01',
            'prop_traffic_01a',
            'prop_traffic_01b',
            'prop_traffic_01d',
            'prop_traffic_02b',
            'prop_traffic_02a',
            'prop_streetlight_11c',
            'prop_streetlight_10',
            'prop_streetlight_12a',
            'prop_streetlight_11b',
            'prop_streetlight_06',
            'prop_streetlight_07a',
            'prop_streetlight_11a',
            'prop_streetlight_15a',
            'prop_streetlight_07b',
            'prop_streetlight_09',
            'prop_snow_streetlight_09',
            'prop_streetlight_12b',
            'prop_streetlight_08',
            'prop_streetlight_04',
            'prop_streetlight_14a',
            'prop_streetlight_02',
            'prop_streetlight_03c',
            'prop_snow_streetlight01',
            'prop_streetlight_05_b',
            'prop_streetlight_03',
            'prop_streetlight_01b',
            'prop_streetlight_03b',
            'prop_streetlight_03d',
            'prop_traffic_03a',
            'prop_snow_streetlight_01_frag_',
            'prop_streetlight_03e',
            'prop_streetlight_05',
            'prop_streetlight_16a',
            'prop_streetlight_01',
            'prop_fire_hydrant_2',
            'prop_fire_hydrant_1',
            'prop_fire_hydrant_4',
            'prop_fire_hydrant_2_l1',
        },
    },
    fields = {
        {
            key = 'models',
            type = 'list',
            itemType = 'text',
            label = 'Modelos',
            help = 'Nome do prop',
        },
        {
            key = 'delay',
            type = 'number',
            label = 'Intervalo da varredura',
            min = 250,
            max = 10000,
            step = 250,
            unit = 'ms',
        },
    },
})
