Mri.module({
    id = 'watercooler',
    label = 'Bebedouros',
    category = 'interaction',
    description = 'Beber água e encher garrafa em bebedouros, fontes e pias pelo olhinho.',
    defaults = {
        enabled = true,
        models = {
            'prop_fountain2',
            'prop_w_fountain_01',
            'prop_fountain1',
            'prop_watercooler',
            'prop_watercooler_dark',
            'prop_sink_02',
            'prop_sink_03',
            'prop_sink_04',
        },
        maxDistance = 3,
        targetDistance = 2,
        fillDuration = 5000,
        emptyBottle = 'empty_water_bottle',
        filledBottle = 'water_bottle',
        hydration = 50,
        excessiveDrinkCount = 3,
        dropTooFar = false,
        dropReason = 'Você está muito longe da fonte de água.',
    },
    fields = {
        {
            key = 'models',
            type = 'list',
            itemType = 'text',
            label = 'Modelos',
            help = 'Nome do prop',
        },
        {
            key = 'targetDistance',
            type = 'number',
            label = 'Distância do olhinho',
            min = 0.5,
            max = 10,
            step = 0.5,
            unit = 'm',
        },
        {
            key = 'maxDistance',
            type = 'number',
            label = 'Distância máxima pra encher',
            min = 0.5,
            max = 10,
            step = 0.5,
            unit = 'm',
        },
        {
            key = 'fillDuration',
            type = 'number',
            label = 'Tempo pra encher',
            min = 500,
            max = 30000,
            step = 500,
            unit = 'ms',
        },
        {
            key = 'emptyBottle',
            type = 'text',
            label = 'Item garrafa vazia',
        },
        {
            key = 'filledBottle',
            type = 'text',
            label = 'Item garrafa cheia',
        },
        {
            key = 'hydration',
            type = 'number',
            label = 'Sede recuperada por gole',
            min = 1,
            max = 100,
        },
        {
            key = 'excessiveDrinkCount',
            type = 'number',
            label = 'Goles seguidos até o aviso',
            min = 1,
            max = 20,
        },
        {
            key = 'dropTooFar',
            type = 'boolean',
            label = 'Derrubar quem enche de longe',
            help = 'Anti-trapaça: expulsa do servidor',
        },
        {
            key = 'dropReason',
            type = 'text',
            label = 'Mensagem ao derrubar',
        },
    },
})
