Mri.module({
    id = 'wheelbreak',
    label = 'Roda solta em batida',
    category = 'vehicles',
    description = 'Uma roda solta em batida forte.',
    defaults = {
        enabled = false,
        mode = 'impact',
        impactDamage = 80,
        minImpactSpeed = 20,
        impactDeltaSpeed = 35,
        cooldown = 5000,
        speed = 85,
    },
    fields = {
        {
            key = 'mode',
            type = 'select',
            label = 'Como detectar',
            options = {
                {
                    value = 'impact',
                    label = 'Força do impacto',
                },
                {
                    value = 'speed',
                    label = 'Velocidade da colisão',
                },
            },
        },
        {
            key = 'impactDamage',
            type = 'number',
            label = 'Dano de lataria de uma vez',
            min = 1,
            max = 1000,
            help = 'Modo impacto. Menor = mais sensível',
        },
        {
            key = 'minImpactSpeed',
            type = 'number',
            label = 'Velocidade mínima do impacto',
            min = 0,
            max = 300,
            unit = 'km/h',
        },
        {
            key = 'impactDeltaSpeed',
            type = 'number',
            label = 'Perda de velocidade de uma vez',
            min = 1,
            max = 300,
            unit = 'km/h',
        },
        {
            key = 'speed',
            type = 'number',
            label = 'Velocidade da colisão',
            min = 0,
            max = 400,
            unit = 'km/h',
            help = 'Modo velocidade',
        },
        {
            key = 'cooldown',
            type = 'number',
            label = 'Intervalo entre quebras',
            min = 0,
            max = 60000,
            step = 500,
            unit = 'ms',
        },
    },
})
