Mri.module({
    id = 'recoil',
    label = 'Recuo realista',
    category = 'combat',
    description = 'Recuo vertical por tipo de arma, mira bêbada, sem headshot de um tiro e sem soco mirando.',
    defaults = {
        enabled = false,
        verticalRecoil = true,
        drunkAiming = false,
        drunkAimingPower = 0.2,
        disableAimPunching = false,
        disableHeadshots = false,
        whitelistedWeapons = { 'WEAPON_SNIPERRIFLE', 'WEAPON_HEAVYSNIPER', 'WEAPON_HEAVYSNIPER_MK2', 'WEAPON_MARKSMANRIFLE', 'WEAPON_MARKSMANRIFLE_MK2' },
        recoilMultipliers = {
            PISTOL = 0.3,
            SMG = 0.8,
            RIFLE = 1.3,
            LMG = 1.6,
            SHOTGUN = 2.3,
            SNIPER = 5.5,
            VEHICLE = 0.8,
        },
    },
    fields = {
        {
            key = 'verticalRecoil',
            type = 'boolean',
            label = 'Recuo vertical',
        },
        {
            key = 'drunkAiming',
            type = 'boolean',
            label = 'Mira bêbada',
            help = 'A câmera treme mirando',
        },
        {
            key = 'drunkAimingPower',
            type = 'number',
            label = 'Força da mira bêbada',
            min = 0,
            max = 2,
            step = 0.05,
        },
        {
            key = 'disableAimPunching',
            type = 'boolean',
            label = 'Sem soco mirando',
        },
        {
            key = 'disableHeadshots',
            type = 'boolean',
            label = 'Sem headshot de um tiro',
        },
        {
            key = 'whitelistedWeapons',
            type = 'list',
            itemType = 'text',
            label = 'Armas sem recuo',
            help = 'Nome da arma, ex.: WEAPON_SNIPERRIFLE',
        },
        {
            key = 'recoilMultipliers',
            type = 'map',
            itemType = 'number',
            label = 'Força do recuo por tipo',
            help = '0 = sem recuo. VEHICLE multiplica atirando de dentro do veículo.',
        },
    },
})
